Fixed DSL graph dependencies and wrapper scripts
Fixed DSL graph dependencies by explicitly writing the dependencies
between resources in the require attribute of the resources of a same
level in the DSL graph

Fixed the wrapper install scripts by modifying the templates, modified
the test of the parsing logs and adding some logs

diff --git a/modules/oracle/templates/wruninstaller_9.2.0.1-template.erb b/modules/oracle/templates/wruninstaller_9.2.0.1-template.erb
--- a/modules/oracle/templates/wruninstaller_9.2.0.1-template.erb
+++ b/modules/oracle/templates/wruninstaller_9.2.0.1-template.erb
@@ -1,60 +1,71 @@
 #!/usr/bin/bash 
 
+EXITCODE=1
 
-echo " Running the oracle silent install ./runInstaller -silent  -responseFile <%= responsefile_path %>  ORACLE_HOME=\"<%= current_oracle_home %>\"  ORACLE_HOME_NAME=\"<%= oracle_patch_version %>\"  UNIX_GROUP_NAME=\"oinstall\"  LOCATION_FOR_DISK2=\"<%= disk2_9201_path %>\"  LOCATION_FOR_DISK3=\"<%= disk3_9201_path %>\"  s_cfgtyperet=\"Software Only\" "
+# Log a message on the output and exit properly                                                                                                                                                             
+log_and_exit()                                                                                                                                                                                              
+{                                                                                                                                                                                                           
+    local type="$1"                                                                                                                                                                                         
+    shift                                                                                                                                                                                                   
+    local message="$*"                                                                                                                                                                                      
+    log $type $message                                                                                                                                                                                      
+    exit $EXITCODE                                                                                                                                                                                          
+}                                                                                                                                                                                                           
+                                                                                                                                                                                                            
+# Log a message on the output                                                                                                                                                                               
+log()                                                                                                                                                                                                       
+{                                                                                                                                                                                                           
+    local type="$1"                                                                                                                                                                                         
+    shift                                                                                                                                                                                                   
+    local message="$*"                                                                                                                                                                                      
+    local dataflags="+%Y.%m.%d,%H:%M:%S"                                                                                                                                                                    
+                                                                                                                                                                                                            
+    echo "[$type] - `date $dataflags` - $message"                                                                                                                                                           
+}    
+
+log "INFO" " Running the oracle silent install ./runInstaller -silent  -responseFile <%= responsefile_path %>  ORACLE_HOME=\"<%= current_oracle_home %>\"  ORACLE_HOME_NAME=\"<%= oracle_patch_version %>\"  UNIX_GROUP_NAME=\"oinstall\"  LOCATION_FOR_DISK2=\"<%= disk2_9201_path %>\"  LOCATION_FOR_DISK3=\"<%= disk3_9201_path %>\"  s_cfgtyperet=\"Software Only\" "
 
 cd <%= disk1_9201_path %>
+log "INFO" "Current wokring directory: `pwd`"
 
+log "INFO" "The runinstaller is starting..."
 ./runInstaller -silent  -responseFile <%= responsefile_path %>  ORACLE_HOME="<%= current_oracle_home %>"  ORACLE_HOME_NAME="<%= oracle_patch_version %>"  UNIX_GROUP_NAME="oinstall"  LOCATION_FOR_DISK2="<%= disk2_9201_path %>"  LOCATION_FOR_DISK3="<%= disk3_9201_path %>"  s_cfgtyperet="Software Only"
+log "INFO" "The runinstaller is started..."
 
+
+sleep 120
 orainventory_path=<%= orainventory_path %>
 oracle_install_log=`ls -lrt ${orainventory_path}/logs |grep oraInstall | grep out | tail -1 | awk '{print $9}'`
 oracle_install_log_path="${orainventory_path}/logs/${oracle_install_log}"
+#oracle_install_log_path=`find ${oracinventory_path}/logs -type f -print| xargs -n 1 -i egrep -l "TOPLEVEL_COMPONENT.*9.2.0.1" {}`
 
-function test_pad()                                                                                                                               
-{                                                                                                                                                 
-        file=$1
 
-        sleep 120
+if [ -e "${oracle_install_log_path}" ]; then                                                                                                                                                                
+    log "INFO" "Found an oracle install log file: ${oracle_install_log_path}"
+else                                                                                                                                                                                                        
+    log_and_exit "ERROR" "Could not find an oracle install log file"
+fi 
+
+
+test_pad()
+{
+        local file=$1                                                                                                                                                                                        
+        sleep 5 
         grep 'was successful' $file
-        if [ $? -eq 1 ]; then return 0; fi
-        
-        return 1                                                                                                                                  
-} 
+        if ((   $? == 0  )); then
+                touch /var/opt/oracle/9.2.0.1_installed
+                EXITCODE=0
+                log_and_exit "INFO" "You have installed 9.2.0.1 database server software"
+        else
+                log "INFO" "Not yet successful..."
+        fi
 
+        return 1
+}
 
-function reverse()                                                                                                                                
-{                                                                                                                                                 
-        string=$1                                                                                                                                 
-        len=$(echo -n $string | wc -c)                                                                                                            
-        while test $len -gt 0                                                                                                                     
-        do                                                                                                                                        
-                rev=$rev$(echo $string | cut -c $len)                                                                                             
-                len=$(( len - 1 ))                                                                                                                
-        done                                                                                                                                      
-        echo $rev                                                                                                                                 
-}                                                                                                                                                 
-                                                                                                                                                  
-ANIM="//--\\||"                                                                                                                                   
-PAD="                                                                  "                                                                          
-SLEEP="0.1"                                                                                                                                       
-                                                                                                                                                  
-ANIM_L="$(reverse $ANIM)"                                                                                                                         
-PAD_LN=${#PAD}                                                                                                                                    
-ANIM_LN=${#ANIM}                                                                                                                                  
-u=0; re=0; l=0                                                                                                                                    
-                                                                                                                                                  
-echo "Parsing log: ${oracle_install_log_path} for successful install message..."
-while test_pad $oracle_install_log_path; do                                                                                                                                
-        if [ $re -eq 1 ]; then L=$ANIM_L; else L=$ANIM; fi                                                                                        
-        if [ $re -eq 1 ]; then p=$(( $PAD_LN - $u )); else p=$u; fi                                                                               
-        echo -ne "${PAD:0:$p} ${L:$l:1} ${PAD:$p:$PAD_LN} \r"                                                                                     
-        if [ $u -eq $PAD_LN ]; then u=0; if [ $re -eq 1 ]; then re=0; else re=1; fi; fi                                                           
-        u=$(( u + 1 )); l=$(( l + 1 ))                                                                                                            
-        if [ $l -eq $ANIM_LN ]; then l=0; fi                                                                                                      
-        sleep $SLEEP                                                                                                                              
-        echo "Parsing log and sleeping $SLEEP..."
+while true; do
+        test_pad ${oracle_install_log_path} 
+        sleep 5 
 done
-touch /var/opt/oracle/9.2.0.1_installed
-echo "The installation of Oracle9i 9.2.0.1 Database was successful."
+
 exit 0
